edition = "2021"
version = "Two"

max_width = 132

struct_lit_width = 0    # default 18 (24)
fn_call_width=100       # default 60 (80)
array_width=132         # default 60 (80)
#chain_width=100        # default 60 (80)
#attr_fn_like_width=100  # default 70 (92)
#single_line_if_else_max_width=100  # default 50 (66)
#struct_variant_width = 0           # default 35 (46)

newline_style = "Unix"
reorder_imports = false
match_block_trailing_comma = true

## Experimental Features
unstable_features = true
blank_lines_upper_bound = 3
overflow_delimited_expr = true

# it would be nice to allow a newline at the top and bottom of file
# it would be nice to not erase the whitespace between the end of the code line and start of a comment on the same line
