name: deploy-docs
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: jetli/wasm-bindgen-action@v0.2.0

      - name: Install dependencies
        run: |
          sudo apt-get install -y alsa-base libasound2-dev libxkbcommon-dev
          cargo install just

      - name: Make build directory
        run: mkdir build

      - name: Build Pixels frontend
        run: |
          cd emulator/frontends/pixels
          just build moa-genesis
          cp -R dist/* ../../../build

      - name: Build docs
        run: |
          cargo doc --document-private-items --workspace
          cp -R target/doc build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
