name: rustfmt
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y alsa-base libasound2-dev libxkbcommon-dev

      - name: Select rust version
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup default nightly

      - name: Check rustfmt
        run: |
          cargo +nightly fmt --check
