name: test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get install -y alsa-base libasound2-dev libxkbcommon-dev

      - name: Select rust version
        run: |
          rustup toolchain install 1.70 --profile minimal --no-self-update
          rustup default 1.70

      - name: Run tests with default features
        run: |
          cargo test

      - name: Run tests with all features
        run: |
          cargo test #--features=std,fugit,femtos

      - name: Run test with no_std
        run: |
          cargo test --no-default-features


